---
- name: Create kubeadm Group
  group:
    name: "{{ kubeadm.os_user.group }}"
    gid: "{{ kubeadm.os_user.gid }}"
    state: present
  become: yes

- name: Create kubeadm User
  user:
    name: "{{ kubeadm.os_user.user }}"
    comment: "{{ kubeadm.os_user.comment }}"
    group: "{{ kubeadm.os_user.group }}"
    groups: "{{ kubeadm.os_user.groups }}"
    uid: "{{ kubeadm.os_user.uid }}"
    shell: "/bin/bash"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present
  become: yes

- name: Collect public keys of kubeadm-users 
  shell: "cat /home/{{ kubeadm.os_user.user }}/.ssh/id_rsa.pub"
  changed_when: False
  become: yes
  register: ssh_public_key

- name: Set SSH-Key for default Admin User
  authorized_key:
    user: "{{ kubeadm.os_user.user }}"
    key: "{{ item.key }}"
    state: present
  become: yes
  with_items:
    - "{{ ssh_keys }}"
  when: item.user in kubernetes_ssh_keys
      
- name: Set SSH-Key for kubernetes-users
  authorized_key:
    user: "{{ item[1] }}"
    key: "{{ item[2] }}"
    state: present
  delegate_to: "{{ item[0] }}"
  ignore_errors: yes
  become: yes
  with_nested:
    - "{{groups['kubernetes']}}"
    - "{{ kubeadm.os_user.user }}"
    - "{{ ssh_public_key.stdout }}"
  when: item[0] in ansible_play_hosts